/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Splash;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import rojerusan.RSAnimation;



/**
 *
 * @author samue
 */
public class Splash extends javax.swing.JFrame {

    
    private Timer t;
    private int n= 0;
    /**
     * Creates new form Splash
     */
    public Splash() {
        initComponents();
        progress.setValue(0);
        progress.setColorBackground(new Color(0,0,0,0));
        pn1.setBackground(new Color(0,0,0,0));
        
        
        rsutilities.RSUtilities.setCentrarVentana(this);
        rsutilities.RSUtilities.setOpaqueVentana(this,false);
        
        
        RSAnimation.setBajar(-400,10,2,2,jlLogo);
        
        ActionListener accion = new ActionListener (){
            @Override
            public void actionPerformed(ActionEvent e) {
                if(n<=100){
                progress.setValue(n);
                n = n+10;
                }else{
                    t.stop();
                    dispose();
                    new Login.login().setVisible(true);
                }
            }
        };
        t = new Timer(300,accion);
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel2 = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();
        progress = new rojerusan.componentes.RSProgressBarSinText();
        pn1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(51, 255, 204));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(0, 51, 204));
        rSPanelGradiente1.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELECTRONICA");
        rSPanelGradiente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 361, 77));

        jlLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Splash/PrimeraFactura_02-400x400.png"))); // NOI18N
        rSPanelGradiente1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 375));

        progress.setForeground(new java.awt.Color(0, 204, 0));
        progress.setValue(20);
        progress.setColorForeground(new java.awt.Color(0, 255, 102));
        progress.setGrosorBorde(0);
        rSPanelGradiente1.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 830, 10));

        pn1.setBackground(new java.awt.Color(0, 0, 0));
        pn1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INSTITUTO TECNICO RICALDONE");
        pn1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, 30));

        rSPanelGradiente1.add(pn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 800, 70));

        rSPanelShadow1.add(rSPanelGradiente1, java.awt.BorderLayout.CENTER);

        getContentPane().add(rSPanelShadow1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JPanel pn1;
    private rojerusan.componentes.RSProgressBarSinText progress;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    // End of variables declaration//GEN-END:variables
}
