/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.Llenar_Tablas;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15-BS020LA
 */
public class Agregar_factura extends javax.swing.JFrame {

    Clases.Llenar_Tablas con = new Llenar_Tablas();
    Clases.Conexion cn = new Clases.Conexion();
    String row;

    public Agregar_factura() {
        initComponents();
        this.jComboBoxTipoFactura.setModel(con.obt_tipo_factura());
        this.jComboBoxCliente.setModel(con.obt_cliente());
        this.jComboBoxTipoPago.setModel(con.obt_tipo_pago());
        txtProducto.setEditable(false);
        txtPrecioUnitario.setEditable(false);
        txtIva.setEditable(false);
        txtIvaTotal.setEditable(false);
        txtsubtotal.setEditable(false);
        txtTotal.setEditable(false);
        setJTexFieldChanged(txtCodigoBarras);
        cargarIVA();
        NumFactura();
        showdate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAtras = new javax.swing.JLabel();
        jComboBoxTipoFactura = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Factura = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        btnAgregaralafactura = new javax.swing.JLabel();
        btnEliminardelafactura = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtIvaTotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtPrecioUnitario = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxTipoPago = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        btnAgregarfactura = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        lblstockactivo = new javax.swing.JLabel();
        lblstockactivo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-atras.png"))); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });

        jComboBoxTipoFactura.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Tipo de Factura:");

        Tabla_Factura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Producto", "Precio Unitario", "Ventas Afectadas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabla_Factura.getTableHeader().setReorderingAllowed(false);
        Tabla_Factura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_FacturaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_Factura);
        if (Tabla_Factura.getColumnModel().getColumnCount() > 0) {
            Tabla_Factura.getColumnModel().getColumn(0).setResizable(false);
            Tabla_Factura.getColumnModel().getColumn(1).setResizable(false);
            Tabla_Factura.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setText("Fecha:");

        jLabel5.setText("Factura N°:");

        btnAgregaralafactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-add.png"))); // NOI18N
        btnAgregaralafactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregaralafacturaMouseClicked(evt);
            }
        });

        btnEliminardelafactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-menos.png"))); // NOI18N
        btnEliminardelafactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminardelafacturaMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Agregar");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setText("Eliminar");

        jLabel7.setText("Cliente:");

        jLabel8.setText("Codigo de Barras:");

        jLabel9.setText("Producto:");

        jLabel14.setText("Cantidad:");

        jLabel17.setText("Precio Unitario: $");

        jLabel18.setText("% IVA:");

        jLabel19.setText("Tipo de Pago:");

        jComboBoxTipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel20.setText("Guardar Factura");

        btnAgregarfactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-guardar.png"))); // NOI18N
        btnAgregarfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarfacturaMouseClicked(evt);
            }
        });

        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("IVA: $");

        jLabel16.setText("SUBTOTAL: $");

        jLabel22.setText("TOTAL: $");

        lblstockactivo1.setText("= Unidades en Inventario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxCliente, 0, 300, Short.MAX_VALUE)
                            .addComponent(jComboBoxTipoPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtProducto)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblstockactivo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(lblstockactivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnAtras)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAgregaralafactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEliminardelafactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtsubtotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                .addComponent(txtIvaTotal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgregarfactura)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(41, 41, 41))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBoxTipoFactura, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(186, 186, 186))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addComponent(btnAtras))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnAgregarfactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel11)
                                                .addComponent(txtIvaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel22)))
                                    .addComponent(btnEliminardelafactura)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblstockactivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)
                                .addComponent(lblstockactivo1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAgregaralafactura, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(24, 24, 24)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setJTexFieldChanged(JTextField txt) {
        DocumentListener documentListener = new DocumentListener() {

            public void changedUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }

            public void insertUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }

            public void removeUpdate(DocumentEvent documentEvent) {
                printIt(documentEvent);
            }
        };
        txt.getDocument().addDocumentListener(documentListener);

    }

    private void printIt(DocumentEvent documentEvent) {
        DocumentEvent.EventType type = documentEvent.getType();

        if (type.equals(DocumentEvent.EventType.CHANGE)) {
            try {
                String codigo = txtCodigoBarras.getText();
                String sql = "select nombre_producto as \"Producto\", stock_activo as \"Stock\", precio_venta_producto as \"Precio\" from producto where codigo_barras = '" + codigo + "' ";
                PreparedStatement ps = cn.Conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String add1 = rs.getString("Producto");
                    txtProducto.setText(add1);
                    String add2 = rs.getString("Stock");
                    lblstockactivo.setText(add2);
                    String add3 = rs.getString("Precio");
                    txtPrecioUnitario.setText(add3);
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        } else if (type.equals(DocumentEvent.EventType.INSERT)) {
            try {
                String codigo = txtCodigoBarras.getText();
                String sql = "select nombre_producto as \"Producto\", stock_activo as \"Stock\", precio_venta_producto as \"Precio\" from producto where codigo_barras = '" + codigo + "' ";
                PreparedStatement ps = cn.Conectar().prepareStatement(sql);
                ResultSet rs = ps.executeQuery();

                if (rs.next()) {
                    String add1 = rs.getString("Producto");
                    txtProducto.setText(add1);
                    String add2 = rs.getString("Stock");
                    lblstockactivo.setText(add2);
                    String add3 = rs.getString("Precio");
                    txtPrecioUnitario.setText(add3);
                }
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        } else if (type.equals(DocumentEvent.EventType.REMOVE)) {
            txtProducto.setText("");
            txtPrecioUnitario.setText("");
        }
    }

    public void NumFactura() {
        Clases.Mto_Factura obj = new Clases.Mto_Factura();
        if (obj.NoFactura()) {
            txtNumeroFactura.setText(String.valueOf(obj.getNumerodefactura()));
            txtNumeroFactura.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(this, "Numero de Factura no encontrado");
        }
    }
    public static String DateFormat = "MM-dd-yyyy";
    DecimalFormat df = new DecimalFormat("#.00");

    public void cargarIVA() {
        try {
            String sql = "select impuesto_factura from impuesto_iva";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("impuesto_factura");
                String impuesto = add1;
                txtIva.setText(String.valueOf(impuesto));
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    public void showdate() {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat format = new SimpleDateFormat(DateFormat);
        txtFecha.setText(format.format(cal.getTime()));
        txtFecha.setEditable(false);
    }

    private void limpiarcampos() {
        txtProducto.setText("");
        txtCantidad.setText("");
        txtPrecioUnitario.setText("");
        lblstockactivo.setText("");
        txtCodigoBarras.setText("");
    }

    public void getsum() {
        Double sum = 0.00;
        for (int i = 0; i < Tabla_Factura.getRowCount(); i++) {
            sum = sum + Double.parseDouble(Tabla_Factura.getValueAt(i, 3).toString());
        }
        txtTotal.setText(Double.toString(sum));
    }
    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        this.dispose();
        Mantenimientos.Facturacion.igualarformabierto = false;
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void btnAgregaralafacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregaralafacturaMouseClicked
        if (jComboBoxTipoFactura.getSelectedItem().toString().equals("Seleccione el tipo de factura")
                || jComboBoxCliente.getSelectedItem().toString().equals("Seleccione a un cliente")
                || jComboBoxTipoPago.getSelectedItem().toString().equals("Seleccione una forma de pago")
                || txtCodigoBarras.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos vacios");
        } else {
            DefaultTableModel model = (DefaultTableModel) Tabla_Factura.getModel();
            Double s1 = Double.parseDouble(txtPrecioUnitario.getText());
            Integer stockactivo = Integer.parseInt(lblstockactivo.getText());
            Integer s2 = Integer.parseInt(txtCantidad.getText());
            if (stockactivo < s2) {
                JOptionPane.showMessageDialog(null, "No puede incluir en la factura inventario inexistente", "Atención!", JOptionPane.WARNING_MESSAGE);
            } else {
                Double s3 = Double.parseDouble(txtIva.getText());
                String s4 = txtCodigoBarras.getText();

                Double precio = s1;

                Double subtotal = precio * s2;
                df.format(subtotal);

                txtsubtotal.setText(String.valueOf(subtotal));

                Double iva = s3;
                Double resultadoiva = subtotal * iva;
                df.format(resultadoiva);

                txtIvaTotal.setText(String.valueOf(resultadoiva));

                df.format(resultadoiva);
                Double resultadototal = resultadoiva + subtotal;

                model.addRow(new Object[]{txtCantidad.getText(), txtProducto.getText(), txtPrecioUnitario.getText(), df.format(resultadototal)});
                limpiarcampos();
                getsum();

                Clases.Mto_Factura obj = new Clases.Mto_Factura();
                obj.setCodigo_barras(s4);
                obj.setStock_activo(s2);
                if (obj.RestarStock()) {
                    JOptionPane.showMessageDialog(this, "Existencias restadas");
                } else {
                    JOptionPane.showMessageDialog(this, "Error al restar las existencias");
                }
            }
        }
    }//GEN-LAST:event_btnAgregaralafacturaMouseClicked

    private void btnAgregarfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarfacturaMouseClicked
        if (jComboBoxTipoFactura.getSelectedItem().toString().equals("Seleccione el tipo de factura")
                || jComboBoxCliente.getSelectedItem().toString().equals("Seleccione a un cliente")
                || jComboBoxTipoPago.getSelectedItem().toString().equals("Seleccione una forma de pago")
                || txtCodigoBarras.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campos vacios");
        }else if (txtTotal.getText().equals("") ){
                JOptionPane.showMessageDialog(this, "La factura no puede tener un total vacio");
                } else {
            Clases.Mto_Factura obj = new Clases.Mto_Factura();
            obj.setFecha_factura(txtFecha.getText());
            obj.setId_tipo_factura(Clases.SQL.getExecuteInt("select id_tipo_factura from tipo_factura where tipo_factura = ?", jComboBoxTipoFactura.getSelectedItem().toString()));
            obj.setId_tpago(Clases.SQL.getExecuteInt("select id_tpago from tipo_pago where tipo_pago = ?", jComboBoxTipoPago.getSelectedItem().toString()));
            obj.setId_cliente(Clases.SQL.getExecuteInt("select id_cliente from cliente where nombre_cliente = ?", jComboBoxCliente.getSelectedItem().toString()));
            obj.setMonto(Double.parseDouble(txtsubtotal.getText()));
            obj.setImpuesto_factura(Double.parseDouble(txtIva.getText()));
            obj.setMonto_con_imp(Double.parseDouble(txtIvaTotal.getText()));
            obj.setMonto_total(Double.parseDouble(txtTotal.getText()));
            if (obj.InsertarFactura()) {
                JOptionPane.showMessageDialog(this, "Factura Creada con Exito");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Error al Crear la Factura");
            }
            limpiarcampos();
        }       
    }//GEN-LAST:event_btnAgregarfacturaMouseClicked

    private void btnEliminardelafacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminardelafacturaMouseClicked
        if (txtCodigoBarras.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Inserte o Escane un codigo de barras");
        } else {
            DefaultTableModel model = (DefaultTableModel) Tabla_Factura.getModel();
            model.removeRow(Tabla_Factura.getSelectedRow());
            Integer s2 = Integer.parseInt(txtCantidad.getText());
            String s4 = txtCodigoBarras.getText();
            Clases.Mto_Factura obj = new Clases.Mto_Factura();
            obj.setCodigo_barras(s4);
            obj.setStock_activo(s2);
            if (obj.SumarStock()) {
                JOptionPane.showMessageDialog(this, "Existencias restauradas");
            } else {
                JOptionPane.showMessageDialog(this, "Error al restaurar las existencias");
            }
            limpiarcampos();
            getsum();
            Double totalf = Double.parseDouble(txtTotal.getText());
            if (totalf == 0.00) {
                txtIvaTotal.setText("");
                txtsubtotal.setText("");
            }
        }
    }//GEN-LAST:event_btnEliminardelafacturaMouseClicked

    private void Tabla_FacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_FacturaMouseClicked
        try {
            int row = Tabla_Factura.getSelectedRow();
            String Cantidad = (Tabla_Factura.getModel().getValueAt(row, 0).toString());
            txtCantidad.setText(Cantidad);
            String Table_click = (Tabla_Factura.getModel().getValueAt(row, 1).toString());
            String sql = "select codigo_barras as \"Codigo de Barras\", nombre_producto as \"Producto\", precio_venta_producto as \"Precio\", stock_activo as \"Stock\" from producto where nombre_producto = '" + Table_click + "' ";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                String add1 = rs.getString("Codigo de Barras");
                txtCodigoBarras.setText(add1);
                String add2 = rs.getString("Producto");
                txtProducto.setText(add2);
                String add3 = rs.getString("Precio");
                txtPrecioUnitario.setText(add3);
                String add4 = rs.getString("Stock");
                lblstockactivo.setText(add4);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_Tabla_FacturaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_factura.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_factura().setVisible(true);
                new Agregar_factura().toFront();
                new Agregar_factura().repaint();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Factura;
    private javax.swing.JLabel btnAgregaralafactura;
    private javax.swing.JLabel btnAgregarfactura;
    private javax.swing.JLabel btnAtras;
    private javax.swing.JLabel btnEliminardelafactura;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxTipoFactura;
    private javax.swing.JComboBox<String> jComboBoxTipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblstockactivo;
    private javax.swing.JLabel lblstockactivo1;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtIvaTotal;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtPrecioUnitario;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtsubtotal;
    // End of variables declaration//GEN-END:variables

}
