package Mantenimientos;

import Atxy2k.CustomTextField.RestrictedTextField;
import Clases.Llenar_Tablas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class Clientes extends javax.swing.JPanel {

    Clases.Llenar_Tablas con = new Llenar_Tablas();
    Clases.Conexion cn = new Clases.Conexion();
/**Metodo para limitar los campos el el mantenimiento **/
    public Clientes() {
        initComponents();
        showTableData();
        lblId.setVisible(false);
        txtId_cliente.setVisible(false);
        txtId_cliente.setEnabled(false);
        txtId_cliente.setEditable(false);
        RestrictedTextField restricted = new RestrictedTextField(txtDui);
        restricted.setLimit(9);
        RestrictedTextField restricted1 = new RestrictedTextField(txtTelefono1);
        restricted1.setLimit(8);
        RestrictedTextField restricted2 = new RestrictedTextField(txtTelefono2);
        restricted2.setLimit(8);
        RestrictedTextField restricted5 = new RestrictedTextField(txtNit);
        restricted5.setLimit(9);
        RestrictedTextField restricted6 = new RestrictedTextField(txtRuc);
        restricted6.setLimit(9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void showTableData() {
        try {
            String sql = "select nombre_cliente as \"Nombre\", apellidos_cliente as \"Apellidos\", fecha_nacimiento as \"Fecha de Nacimiento\", compania as \"Nombre de Empresa\", direccion1 as \"Dirección 1\", direccion2 as \"Dirección 2\", telefono1 as \"Telefono 1\", telefono2 as \"Telefono 2\", email_cliente as \"Email\", nit_c as \"NIT\", dui_c as \"DUI\", ruc_C as \"RUC\" from cliente, estado where cliente.id_estado=estado.id_estado and estado.id_estado = 1";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            Tabla_cliente.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtId_cliente = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtDui = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_cliente = new javax.swing.JTable();
        btn_Agregar = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        txt_buscar_nombre = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccion1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccion2 = new javax.swing.JTextArea();
        txtNombre_cliente = new javax.swing.JTextField();
        txtApellido_cliente = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(968, 678));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Fecha de nacimiento:");

        txtEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmpresaKeyTyped(evt);
            }
        });

        jLabel4.setText("Empresa:");

        jLabel5.setText("Dirección N°1:");

        jLabel6.setText("Dirección N°2:");

        jLabel7.setText("Email:");

        txtTelefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono1KeyTyped(evt);
            }
        });

        jLabel8.setText("Telefono N°1:");

        txtTelefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefono2KeyTyped(evt);
            }
        });

        jLabel9.setText("Telefono N°2:");

        lblId.setText("ID");

        jLabel11.setText("DUI:");

        txtDui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuiActionPerformed(evt);
            }
        });
        txtDui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDuiKeyTyped(evt);
            }
        });

        txtNit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNitActionPerformed(evt);
            }
        });
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });

        jLabel12.setText("NIT:");

        txtRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRucActionPerformed(evt);
            }
        });
        txtRuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRucKeyTyped(evt);
            }
        });

        jLabel13.setText("RUC:");

        Tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_cliente);

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-add.png"))); // NOI18N
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseClicked(evt);
            }
        });

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-limpiar.png"))); // NOI18N
        btn_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_limpiarMouseClicked(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-delete.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-update.png"))); // NOI18N
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-buscar.png"))); // NOI18N
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });

        txt_buscar_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_nombreKeyTyped(evt);
            }
        });

        txtDireccion1.setColumns(20);
        txtDireccion1.setLineWrap(true);
        txtDireccion1.setRows(5);
        jScrollPane2.setViewportView(txtDireccion1);

        txtDireccion2.setColumns(20);
        txtDireccion2.setLineWrap(true);
        txtDireccion2.setRows(5);
        jScrollPane3.setViewportView(txtDireccion2);

        txtNombre_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_clienteActionPerformed(evt);
            }
        });
        txtNombre_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_clienteKeyTyped(evt);
            }
        });

        txtApellido_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellido_clienteActionPerformed(evt);
            }
        });
        txtApellido_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido_clienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txt_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(lblId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283)
                        .addComponent(btn_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Agregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtNombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(txtNombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtApellido_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_buscar_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId)
                            .addComponent(txtId_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_Agregar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_eliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuiActionPerformed

    private void txtNitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNitActionPerformed

    private void txtRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRucActionPerformed

    private void btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseClicked

        if (txtNombre_cliente.getText().equals("")
                || txtApellido_cliente.getText().equals("")
                || txtFecha.getText().equals("")
                || txtEmpresa.getText().equals("")
                || txtDireccion1.getText().equals("")
                || txtDireccion2.getText().equals("")
                || txtEmail.getText().equals("")
                || txtTelefono1.getText().equals("")
                || txtTelefono2.getText().equals("")
                || txtDui.getText().equals("")
                || txtNit.getText().equals("")
                || txtRuc.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Campos vacios");
        } else {
            Clases.Mto_Clientes obj = new Clases.Mto_Clientes();
            if (obj.esEmail(txtEmail.getText())) {
                obj.setNombre_cliente(txtNombre_cliente.getText());
                obj.setApellidos_cliente(txtApellido_cliente.getText());
                obj.setFecha_nacimiento(txtFecha.getText());
                obj.setCompania(txtEmpresa.getText());
                obj.setDireccion1(txtDireccion1.getText());
                obj.setDireccion2(txtDireccion2.getText());
                obj.setTelefono1(txtTelefono1.getText());
                obj.setTelefono2(txtTelefono2.getText());
                obj.setEmail_cliente(txtEmail.getText());
                obj.setNit_c(txtNit.getText());
                obj.setDui_c(txtDui.getText());
                obj.setRuc_C(txtRuc.getText());
                if (obj.GuardarCliente()) {
                    JOptionPane.showMessageDialog(this, "Cliente guardado");
                    showTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "el correo electronico no es valido");
            }
        }
    }//GEN-LAST:event_btn_AgregarMouseClicked
/**Metodo para la accion del mouse de limpiar el campo**/
    private void btn_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_limpiarMouseClicked
        txtNombre_cliente.setText("");
        txtApellido_cliente.setText("");
        txtFecha.setText("");
        txtEmpresa.setText("");
        txtDireccion1.setText("");
        txtDireccion2.setText("");
        txtEmail.setText("");
        txtTelefono1.setText("");
        txtTelefono2.setText("");
        txtDui.setText("");
        txtNit.setText("");
        txtRuc.setText("");
    }//GEN-LAST:event_btn_limpiarMouseClicked
/**Metodo para la accion del mouse de eliminar el campo**/
    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        Clases.Mto_Clientes obj = new Clases.Mto_Clientes();
        if (txtId_cliente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Para eliminar un cliente, seleccione el cliente a eliminar en la tabla");
        } else {
            obj.setId_cliente(Integer.parseInt(txtId_cliente.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el cliente?", "Precacución", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (eliminar == 0) {
                if (obj.EliminarCliente()) {
                    JOptionPane.showMessageDialog(this, "Cliente eliminado con exito");
                    showTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al eliminar el cliente, consulte con un Administrador");
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked
/**Metodo para la accion del mouse de actualizar el campo del formulario**/
    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        if (txtNombre_cliente.getText().equals("")
                || txtApellido_cliente.getText().equals("")
                || txtFecha.getText().equals("")
                || txtEmpresa.getText().equals("")
                || txtDireccion1.getText().equals("")
                || txtDireccion2.getText().equals("")
                || txtEmail.getText().equals("")
                || txtTelefono1.getText().equals("")
                || txtTelefono2.getText().equals("")
                || txtDui.getText().equals("")
                || txtNit.getText().equals("")
                || txtRuc.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Campos vacios");
        } else {
            Clases.Mto_Clientes obj = new Clases.Mto_Clientes();
            if (obj.esEmail(txtEmail.getText())) {
                obj.setNombre_cliente(txtNombre_cliente.getText());
                obj.setApellidos_cliente(txtApellido_cliente.getText());
                obj.setFecha_nacimiento(txtFecha.getText());
                obj.setCompania(txtEmpresa.getText());
                obj.setDireccion1(txtDireccion1.getText());
                obj.setDireccion2(txtDireccion2.getText());
                obj.setTelefono1(txtTelefono1.getText());
                obj.setTelefono2(txtTelefono2.getText());
                obj.setEmail_cliente(txtEmail.getText());
                obj.setNit_c(txtNit.getText());
                obj.setDui_c(txtDui.getText());
                obj.setRuc_C(txtRuc.getText());
                if (obj.ModificarCliente()) {
                    JOptionPane.showMessageDialog(this, "Cliente modificados");
                    showTableData();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al modificar datos");
                }
            } else {
                JOptionPane.showMessageDialog(null, "el correo electronico no es valido");
            }
        }
    }//GEN-LAST:event_btn_actualizarMouseClicked
/**Metodo para la accion del mouse de buscar un cliente por alguna de las opciones pertinentes**/
    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        Clases.Mto_Clientes obj = new Clases.Mto_Clientes();
        if (txt_buscar_nombre.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nombre vacio, Para realizar una busqueda inserte el nombre del cliente");
        } else {
            obj.setNombre_cliente(txt_buscar_nombre.getText());
            if (obj.ConsultarProducto()) {
                txtNombre_cliente.setText(obj.getNombre_cliente());
                txtApellido_cliente.setText(obj.getApellidos_cliente());
                txtFecha.setText(obj.getFecha_nacimiento());
                txtEmpresa.setText(obj.getCompania());
                txtDireccion1.setText(obj.getDireccion1());
                txtDireccion2.setText(obj.getDireccion2());
                txtEmail.setText(obj.getEmail_cliente());
                txtTelefono1.setText(String.valueOf(obj.getTelefono1()));
                txtTelefono2.setText(String.valueOf(obj.getTelefono2()));
                txtDui.setText(String.valueOf(obj.getDui_c()));
                txtNit.setText(String.valueOf(obj.getNit_c()));
                txtRuc.setText(String.valueOf(obj.getRuc_C()));
            } else {
                JOptionPane.showMessageDialog(this, "Cliente no encontrado");
            }
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void Tabla_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_clienteMouseClicked
        try {
            int row = Tabla_cliente.getSelectedRow();
            String Table_click = (Tabla_cliente.getModel().getValueAt(row, 0).toString());
            String sql = "select id_cliente, nombre_cliente as \"Nombre\", apellidos_cliente as \"Apellidos\", fecha_nacimiento as \"Fecha de Nacimiento\", compania as \"Nombre de Empresa\", direccion1 as \"Dirección 1\", direccion2 as \"Dirección 2\", telefono1 as \"Telefono 1\", telefono2 as \"Telefono 2\", email_cliente as \"Email\", nit_c as \"NIT\", dui_c as \"DUI\", ruc_C as \"RUC\" from cliente, estado where cliente.id_estado=estado.id_estado and estado.id_estado = 1 and nombre_cliente = '" + Table_click + "' ";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("id_cliente");
                txtId_cliente.setText(String.valueOf(add1.trim()));
                String add2 = rs.getString("Nombre");
                txtNombre_cliente.setText(add2.trim());
                String add3 = rs.getString("Apellidos");
                txtApellido_cliente.setText(add3.trim());
                String add4 = rs.getString("Fecha de Nacimiento");
                txtFecha.setText(add4);
                String add5 = rs.getString("Nombre de Empresa");
                txtEmpresa.setText(add5);
                String add6 = rs.getString("Dirección 1");
                txtDireccion1.setText(add6);
                String add7 = rs.getString("Dirección 2");
                txtDireccion2.setText(add7);
                String add8 = rs.getString("Telefono 1");
                txtTelefono1.setText(add8);
                String add9 = rs.getString("Telefono 2");
                txtTelefono2.setText(add9);
                String add10 = rs.getString("Email");
                txtEmail.setText(add10);
                String add11 = rs.getString("NIT");
                txtNit.setText(add11);
                String add12 = rs.getString("DUI");
                txtDui.setText(add12);
                String add13 = rs.getString("RUC");
                txtRuc.setText(add13);
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_Tabla_clienteMouseClicked

    private void txtTelefono1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono1KeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefono1KeyTyped

    private void txtTelefono2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefono2KeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefono2KeyTyped

    private void txtDuiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDuiKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDuiKeyTyped

    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNitKeyTyped

    private void txtRucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRucKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtRucKeyTyped

    private void txt_buscar_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_nombreKeyTyped
        char car = evt.getKeyChar();
            if(Character.isLetter(car)){

        }else{
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_buscar_nombreKeyTyped

    private void txtNombre_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_clienteActionPerformed

    private void txtNombre_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_clienteKeyTyped
       char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isWhitespace(car)) {
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombre_clienteKeyTyped

    private void txtApellido_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellido_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido_clienteActionPerformed

    private void txtApellido_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido_clienteKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isWhitespace(car)) {
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtApellido_clienteKeyTyped

    private void txtEmpresaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmpresaKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtEmpresaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_cliente;
    private javax.swing.JLabel btn_Agregar;
    private javax.swing.JLabel btn_actualizar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel btn_limpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblId;
    private javax.swing.JTextField txtApellido_cliente;
    private javax.swing.JTextArea txtDireccion1;
    private javax.swing.JTextArea txtDireccion2;
    private javax.swing.JTextField txtDui;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtId_cliente;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre_cliente;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtTelefono1;
    private javax.swing.JTextField txtTelefono2;
    private javax.swing.JTextField txt_buscar_nombre;
    // End of variables declaration//GEN-END:variables
}
