
package Mantenimientos;

import Clases.Llenar_Tablas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import rojerusan.RSNotifyFade;

/**Metodo para la conexion del mantenimiento con su clase **/
public class MantenimientoTipoFactura extends javax.swing.JPanel {
    Clases.Llenar_Tablas con = new Llenar_Tablas();
    Clases.Conexion cn = new Clases.Conexion();

    public MantenimientoTipoFactura() {
        initComponents();
        showTableData();
        jLabel10.setVisible(false);
        txtITF.setVisible(false);
        txtITF.setEnabled(false);
        txtITF.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void limpiar(){
    txtITF.setText("");
    txtNomTF.setText("");
    }
    private void showTableData(){
    try{
        String sql = "select tipo_factura as \"Nombre\" From tipo_factura where id_estado = 1";
        PreparedStatement ps = cn.Conectar().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();   
        Tabla_tipoFac.setModel(DbUtils.resultSetToTableModel(rs));         
    }
    catch(SQLException ex){
    JOptionPane.showMessageDialog(null, ex);
    }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomTF = new javax.swing.JTextField();
        txtITF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_tipoFac = new javax.swing.JTable();
        btn_Agregar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        txt_buscar_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Tipo Factura");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNomTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTFActionPerformed(evt);
            }
        });
        txtNomTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomTFKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomTFKeyTyped(evt);
            }
        });
        add(txtNomTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 170, 30));
        add(txtITF, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 34, -1));

        jLabel10.setText("ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Tabla_tipoFac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_tipoFac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_tipoFacMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_tipoFac);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 520, 410));

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-add.png"))); // NOI18N
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseClicked(evt);
            }
        });
        add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-delete.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-update.png"))); // NOI18N
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-buscar.png"))); // NOI18N
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));
        add(txt_buscar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 148, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nombre:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseClicked

        if (txtNomTF.getText().equals(""))
                    {

            new rojerusan.RSNotifyFade("WARNING","Para agregar un tipo de factura, no debe exitir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
        else{
            ClasesMetodos.MetodosTipoFactura obj = new ClasesMetodos.MetodosTipoFactura();
            obj.setNombre(txtNomTF.getText());
            
            if(obj.AgregarTipoFactura()){
                new rojerusan.RSNotifyFade("CORRECTO","Tipo de factura guardada con exito",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                showTableData();
                limpiar();
            }else{
               new rojerusan.RSNotifyFade("ERROR","Error al guardar tipo de factura",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_AgregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        ClasesMetodos.MetodosTipoFactura obj = new ClasesMetodos.MetodosTipoFactura();
        if(txtITF.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Para eliminar un mantenimiento, seleccione el mantenimiento a eliminar en la tabla");
        }else {
            obj.setId(Integer.parseInt(txtITF.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el mantenimiento?", "Precacución", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                if(obj.EliminarTipoFactura()){
                    new rojerusan.RSNotifyFade("CORRECTO","Tipo de factura eliminado correctamente",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                }else{
                    new rojerusan.RSNotifyFade("ERROR","Error al eliminar tipo de factura",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        if (txtNomTF.getText().equals(""))
        {

            new rojerusan.RSNotifyFade("WARNING","Para modificar un tipo de factura, no debe exitir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
        else{
                 ClasesMetodos.MetodosTipoFactura obj = new ClasesMetodos.MetodosTipoFactura();
                obj.setNombre(txtNomTF.getText());
                obj.setId(Integer.parseInt(txtITF.getText()));
                if(obj.ModificarTipoFactura()){
                  new rojerusan.RSNotifyFade("CORRECTO","Tipo de factura modificado correctamente",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                    limpiar();
                }else{
                    JOptionPane.showMessageDialog(this, "Error al modificar datos");
                }
            }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        ClasesMetodos.MetodosTipoFactura obj = new ClasesMetodos.MetodosTipoFactura();
        if (txt_buscar_nombre.getText().equals("")){
            new rojerusan.RSNotifyFade("WARNING","Para buscar un tipo de factura, no debe existir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }else {
            obj.setNombre(txt_buscar_nombre.getText());
            if(obj.BuscarTipoFactura(obj)){              
                txtNomTF.setText(obj.getNombre()); 
                txtITF.setText(String.valueOf(obj.getId()));
            } else {
                new rojerusan.RSNotifyFade("ERROR","Tipo de factura no encontrado",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void Tabla_tipoFacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_tipoFacMouseClicked
     try{
            int row = Tabla_tipoFac.getSelectedRow();
            String Table_click=(Tabla_tipoFac.getModel().getValueAt(row, 0).toString());
            String sql= "select id_tipo_factura as \"Id\", tipo_factura as \"Nombre\" From tipo_factura where tipo_factura = '"+Table_click+"' ";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
            String add1 = rs.getString("Id");
            txtITF.setText(add1);
            String add2 = rs.getString("Nombre");
            txtNomTF.setText(add2);
                     
            }
        }catch(Exception e){
     System.out.println(e.toString());
    }
    }//GEN-LAST:event_Tabla_tipoFacMouseClicked

    private void txtNomTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomTFActionPerformed

    private void txtNomTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomTFKeyPressed

    }//GEN-LAST:event_txtNomTFKeyPressed

    private void txtNomTFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomTFKeyTyped
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isWhitespace(car)) {
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNomTFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_tipoFac;
    private javax.swing.JLabel btn_Agregar;
    private javax.swing.JLabel btn_actualizar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtITF;
    private javax.swing.JTextField txtNomTF;
    private javax.swing.JTextField txt_buscar_nombre;
    // End of variables declaration//GEN-END:variables
}
