
package Mantenimientos;

import Clases.Llenar_Tablas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import rojerusan.RSNotifyFade;

/**Metodo para la conexion del mantenimiento con su clase **/
public class MantenimientoCategoria extends javax.swing.JPanel {
    Clases.Llenar_Tablas con = new Llenar_Tablas();
    Clases.Conexion cn = new Clases.Conexion();

    public MantenimientoCategoria() {
        initComponents();
        showTableData();
        jLabel10.setVisible(false);
        txtId_cliente.setVisible(false);
        txtId_cliente.setEnabled(false);
        txtId_cliente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void showTableData(){
    try{
        String sql = "select nombre_categoria as \"Nombre\", descripcion_categoria as \"Descripcion\" from categoria where id_estado = 1";
        PreparedStatement ps = cn.Conectar().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();   
        Tabla_cliente.setModel(DbUtils.resultSetToTableModel(rs));         
    }
    
    
    catch(SQLException ex){
    JOptionPane.showMessageDialog(null, ex);
    }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre_usuario = new javax.swing.JTextField();
        txtId_cliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_cliente = new javax.swing.JTable();
        btn_Agregar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        txt_buscar_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Categoria");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNombre_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombre_usuarioActionPerformed(evt);
            }
        });
        txtNombre_usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombre_usuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_usuarioKeyTyped(evt);
            }
        });
        add(txtNombre_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 30));
        add(txtId_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 34, -1));

        jLabel10.setText("ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_cliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 520, 410));

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-add.png"))); // NOI18N
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseClicked(evt);
            }
        });
        add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-delete.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-update.png"))); // NOI18N
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-buscar.png"))); // NOI18N
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));
        add(txt_buscar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 148, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Descripcion:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 260, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseClicked

        if (txtNombre_usuario.getText().equals("") || jTextArea1.getText().equals(""))
                    {

            new rojerusan.RSNotifyFade("INFORMATION","Para agregar un mantenimiento, no debe de haber campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }
        else{
            ClasesMetodos.MetodosCategoria obj = new ClasesMetodos.MetodosCategoria();
            obj.setNombre(txtNombre_usuario.getText());
            obj.setDescripcion(jTextArea1.getText());
            if(obj.AgregarTipoFactura()){
                new rojerusan.RSNotifyFade("CORRECTO","El mantenimiento estado ha sido guardado",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                showTableData();
            }else{
               new rojerusan.RSNotifyFade("ERROR","No fue posible agregar el mantenimiento",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_AgregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
        ClasesMetodos.MetodosCategoria obj = new ClasesMetodos.MetodosCategoria();
        if(txtId_cliente.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Para eliminar un mantenimiento, seleccione el mantenimiento a eliminar en la tabla");
        }else {
            obj.setId(Integer.parseInt(txtId_cliente.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el mantenimiento?", "Precacución", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                if(obj.EliminarTipoFactura()){
                    new rojerusan.RSNotifyFade("CORRECTO","El mantenimiento estado ha sido guardado",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                }else{
                    new rojerusan.RSNotifyFade("ERROR","No fue posible eliminar el mantenimiento",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        if (txtNombre_usuario.getText().equals("") || jTextArea1.getText().equals(""))
        {

             new rojerusan.RSNotifyFade("INFORMATION","Para modificar un mantenimiento, no debe de haber campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }
        else{
                ClasesMetodos.MetodosCategoria obj = new ClasesMetodos.MetodosCategoria();
                obj.setNombre(txtNombre_usuario.getText());
                obj.setDescripcion(jTextArea1.getText());
                obj.setId(Integer.parseInt(txtId_cliente.getText()));
                if(obj.ModificarTipoFactura()){
                    new rojerusan.RSNotifyFade("CORRECTO","Datos modificados",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                }else{
                    new rojerusan.RSNotifyFade("ERROR","No fue posible modificar el mantenimiento",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        ClasesMetodos.MetodosCategoria obj = new ClasesMetodos.MetodosCategoria();
        if (txt_buscar_nombre.getText().equals("")){
             new rojerusan.RSNotifyFade("INFORMATION","Para buscar un mantenimiento, no debe de haber campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.INFORMATION).setVisible(true);
        }else {
            obj.setNombre(txt_buscar_nombre.getText());
            if(obj.BuscarTipoFactura(obj)){              
                txtId_cliente.setText(String.valueOf(obj.getId()));
                txtNombre_usuario.setText(obj.getNombre());  
                jTextArea1.setText(obj.getDescripcion());
            } else {
                new rojerusan.RSNotifyFade("ERROR","No fue posible encontrar el mantenimiento",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void Tabla_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_clienteMouseClicked
       try{
            int row = Tabla_cliente.getSelectedRow();
            String Table_click=(Tabla_cliente.getModel().getValueAt(row, 0).toString());
            String sql= "select id_categoria as \"Id\", nombre_categoria as \"Nombre\", descripcion_categoria as \"Descripcion\" from categoria where nombre_categoria = '"+Table_click+"' ";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
            String add1 = rs.getString("Id");
            txtId_cliente.setText(add1);
            String add2 = rs.getString("Nombre");
            txtNombre_usuario.setText(add2);
            String add3 = rs.getString("Descripcion");
            jTextArea1.setText(add3);
            
                     
            }
        }catch(Exception e){
     System.out.println(e.toString());
    }
    }//GEN-LAST:event_Tabla_clienteMouseClicked

    private void txtNombre_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre_usuarioActionPerformed

    private void txtNombre_usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_usuarioKeyPressed

    }//GEN-LAST:event_txtNombre_usuarioKeyPressed

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void txtNombre_usuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_usuarioKeyTyped
       char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isWhitespace(car)) {
        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNombre_usuarioKeyTyped

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
       char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)|| Character.isWhitespace(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_jTextArea1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_cliente;
    private javax.swing.JLabel btn_Agregar;
    private javax.swing.JLabel btn_actualizar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtId_cliente;
    private javax.swing.JTextField txtNombre_usuario;
    private javax.swing.JTextField txt_buscar_nombre;
    // End of variables declaration//GEN-END:variables
}
