
package Mantenimientos;

import Clases.Llenar_Tablas;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import rojerusan.RSNotifyFade;

/**Metodo para la conexion del mantenimiento con su clase **/
public class MantenimientoTipoPago extends javax.swing.JPanel {
    Clases.Llenar_Tablas con = new Llenar_Tablas();
    Clases.Conexion cn = new Clases.Conexion();

    public MantenimientoTipoPago() {
        initComponents();
        showTableData();
        jLabel10.setVisible(false);
        txtITP.setVisible(false);
        txtITP.setEnabled(false);
        txtITP.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void limpiar(){
    txtITP.setText("");
    txtNomTP.setText("");
    txtDTP.setText("");
    }
    private void showTableData(){
    try{
        String sql = "select tipo_pago as \"Nombre\", detalles as \"Descripcion\" From tipo_pago where id_estado = 1";
        PreparedStatement ps = cn.Conectar().prepareStatement(sql);
        ResultSet rs = ps.executeQuery();   
        Tabla_cliente.setModel(DbUtils.resultSetToTableModel(rs));         
    }
    
    
    catch(SQLException ex){
    JOptionPane.showMessageDialog(null, ex);
    }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNomTP = new javax.swing.JTextField();
        txtITP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_cliente = new javax.swing.JTable();
        btn_Agregar = new javax.swing.JLabel();
        btn_eliminar = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JLabel();
        txt_buscar_nombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDTP = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Tipo pago");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtNomTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomTPActionPerformed(evt);
            }
        });
        txtNomTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomTPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomTPKeyTyped(evt);
            }
        });
        add(txtNomTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 200, 30));

        txtITP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtITPActionPerformed(evt);
            }
        });
        add(txtITP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 34, -1));

        jLabel10.setText("ID");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        Tabla_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla_cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_clienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla_cliente);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 520, 410));

        btn_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-add.png"))); // NOI18N
        btn_Agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AgregarMouseClicked(evt);
            }
        });
        add(btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, -1, -1));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-delete.png"))); // NOI18N
        btn_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_eliminarMouseClicked(evt);
            }
        });
        add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, -1, -1));

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-update.png"))); // NOI18N
        btn_actualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_actualizarMouseClicked(evt);
            }
        });
        add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, -1, -1));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-buscar.png"))); // NOI18N
        btn_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_buscarMouseClicked(evt);
            }
        });
        add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        txt_buscar_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_buscar_nombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_buscar_nombreKeyTyped(evt);
            }
        });
        add(txt_buscar_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 148, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Detalles:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Nombre:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        txtDTP.setColumns(20);
        txtDTP.setRows(5);
        txtDTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDTPKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDTPKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtDTP);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 260, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AgregarMouseClicked

        if (txtNomTP.getText().equals("") || txtDTP.getText().equals(""))
                    {

            new rojerusan.RSNotifyFade("WARNING","Para agregar un tipo de factura, no debe exitir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
        else{
            ClasesMetodos.MetodosTipoPago obj = new  ClasesMetodos.MetodosTipoPago();
            obj.setNombre(txtNomTP.getText());
            obj.setDescripcion(txtDTP.getText());
            if(obj.AgregarTipoFactura()){
               new rojerusan.RSNotifyFade("CORRECTO","Tipo de pago agregado con exito",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                showTableData();
                limpiar();
            }else{
               new rojerusan.RSNotifyFade("ERROR","Error al guardar tipo de pago",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_AgregarMouseClicked

    private void btn_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_eliminarMouseClicked
       ClasesMetodos.MetodosTipoPago obj = new  ClasesMetodos.MetodosTipoPago();
        if(txtITP.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Para eliminar un mantenimiento, seleccione el mantenimiento a eliminar en la tabla");
        }else {
            obj.setId(Integer.parseInt(txtITP.getText()));
            int eliminar = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el mantenimiento?", "Precacución", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if(eliminar == 0){
                if(obj.EliminarTipoFactura()){
                  new rojerusan.RSNotifyFade("CORRECTO","Tipo de pago eliminado con exito",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                    limpiar();
                }else{
                 new rojerusan.RSNotifyFade("ERROR","Error al eliminar tipo de pago",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btn_eliminarMouseClicked

    private void btn_actualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_actualizarMouseClicked
        if (txtNomTP.getText().equals("") || txtDTP.getText().equals(""))
        {

           new rojerusan.RSNotifyFade("WARNING","Para actualizar un tipo de factura, no debe exitir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }
        else{
                ClasesMetodos.MetodosTipoPago obj = new  ClasesMetodos.MetodosTipoPago();
                obj.setId(Integer.parseInt(txtITP.getText()));
                obj.setNombre(txtNomTP.getText());
                obj.setDescripcion(txtDTP.getText());
                if(obj.ModificarTipoFactura()){
                   new rojerusan.RSNotifyFade("CORRECTO","Tipo de pago actualizado con exito",7,RSNotifyFade.PositionNotify.TopRight,RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
                    showTableData();
                    limpiar();
                }else{
                    new rojerusan.RSNotifyFade("ERROR","Error al actualizar tipo de pago",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
                }
            }
    }//GEN-LAST:event_btn_actualizarMouseClicked

    private void btn_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_buscarMouseClicked
        ClasesMetodos.MetodosTipoPago obj = new  ClasesMetodos.MetodosTipoPago();
        if (txt_buscar_nombre.getText().equals("")){
        new rojerusan.RSNotifyFade("WARNING","Para realizar una busqueda de un tipo de factura, no debe exitir campos vacios",7,RSNotifyFade.PositionNotify.BottomRight,RSNotifyFade.TypeNotify.WARNING).setVisible(true);
        }else {
            obj.setNombre(txt_buscar_nombre.getText());
            if(obj.BuscarTipoFactura(obj)){  
                txtITP.setText(String.valueOf(obj.getId()));
                txtNomTP.setText(obj.getNombre());  
                txtDTP.setText(obj.getDescripcion());
            } else {
               new rojerusan.RSNotifyFade("ERROR","Error al encontrar tipo de pago",7,RSNotifyFade.PositionNotify.TopLef,RSNotifyFade.TypeNotify.ERROR).setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_buscarMouseClicked

    private void Tabla_clienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_clienteMouseClicked
        try{
            int row = Tabla_cliente.getSelectedRow();
            String Table_click=(Tabla_cliente.getModel().getValueAt(row, 0).toString());
            String sql= "select id_tpago as \"Id\", tipo_pago as \"Nombre\", detalles as \"Descripcion\" From tipo_pago where tipo_pago = '"+Table_click+"' ";
            PreparedStatement ps = cn.Conectar().prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
            String add1 = rs.getString("Id");
            txtITP.setText(add1);
            String add2 = rs.getString("Nombre");
            txtNomTP.setText(add2);
            String add3 = rs.getString("Descripcion");
            txtDTP.setText(add3);
            
                     
            }
        }catch(Exception e){
     System.out.println(e.toString());
    }
    }//GEN-LAST:event_Tabla_clienteMouseClicked

    private void txtITPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtITPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtITPActionPerformed

    private void txtNomTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomTPActionPerformed
        
    }//GEN-LAST:event_txtNomTPActionPerformed

    private void txtNomTPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomTPKeyPressed
        
    }//GEN-LAST:event_txtNomTPKeyPressed

    private void txtDTPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDTPKeyPressed
       
    }//GEN-LAST:event_txtDTPKeyPressed

    private void txt_buscar_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_nombreKeyPressed
       
    }//GEN-LAST:event_txt_buscar_nombreKeyPressed

    private void txtNomTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomTPKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtNomTPKeyTyped

    private void txtDTPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDTPKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txtDTPKeyTyped

    private void txt_buscar_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscar_nombreKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        if (Character.isLetter(car) || Character.isDigit(car)) {

        } else {
            evt.consume();
            getToolkit().beep();
        }
    }//GEN-LAST:event_txt_buscar_nombreKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_cliente;
    private javax.swing.JLabel btn_Agregar;
    private javax.swing.JLabel btn_actualizar;
    private javax.swing.JLabel btn_buscar;
    private javax.swing.JLabel btn_eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDTP;
    private javax.swing.JTextField txtITP;
    private javax.swing.JTextField txtNomTP;
    private javax.swing.JTextField txt_buscar_nombre;
    // End of variables declaration//GEN-END:variables
}
