/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios.Menus;
import Login.login;
import Clases.CambiaPanel;
import Mantenimientos.Clientes;
import Mantenimientos.Facturacion;
import Mantenimientos.Inventario;
import Mantenimientos.Usuarios;
/**
 *
 * @author MARIA
 */
public class Menu_usuario extends javax.swing.JFrame {

    /**
     * Creates new form Menu_usuario
     */
    public Menu_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        rSPanelGradiente1 = new rspanelgradiente.RSPanelGradiente();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnFacAdmin = new rojerusan.RSButtonIconD();
        btnInvAdmin = new rojerusan.RSButtonIconD();
        btnCliAdmin = new rojerusan.RSButtonIconD();
        btnRepAdmin = new rojerusan.RSButtonIconD();
        btnAyuAdmin = new rojerusan.RSButtonIconD();
        btnsalirAd = new rojerusan.RSButtonIconD();
        jSeparator1 = new javax.swing.JSeparator();
        rSPanelGradiente2 = new rspanelgradiente.RSPanelGradiente();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setName(""); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setLayout(new javax.swing.BoxLayout(Contenedor, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 106, 1112, 650));

        rSPanelGradiente1.setColorPrimario(new java.awt.Color(153, 255, 204));
        rSPanelGradiente1.setColorSecundario(new java.awt.Color(51, 102, 255));
        rSPanelGradiente1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Factura");
        rSPanelGradiente1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("  Electronica ");
        rSPanelGradiente1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/favicon.png"))); // NOI18N
        rSPanelGradiente1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 179, -1));

        btnFacAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnFacAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_receipt_3339034.png"))); // NOI18N
        btnFacAdmin.setText("Factura ");
        btnFacAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacAdminActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnFacAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 50));

        btnInvAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnInvAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_editor-documents-files-glyph_763367.png"))); // NOI18N
        btnInvAdmin.setText("Inventario");
        btnInvAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvAdminActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnInvAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 220, 50));

        btnCliAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnCliAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_group-customers-team-contacts-family_3209291.png"))); // NOI18N
        btnCliAdmin.setText("Clientes");
        btnCliAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliAdminActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnCliAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 220, 50));

        btnRepAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnRepAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_b-78_4230296 (1).png"))); // NOI18N
        btnRepAdmin.setText("Reportes");
        btnRepAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepAdminActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnRepAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 220, 50));

        btnAyuAdmin.setBackground(new java.awt.Color(204, 204, 255));
        btnAyuAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_conversation-help-online-communication-message_3802024.png"))); // NOI18N
        btnAyuAdmin.setText("Ayuda");
        rSPanelGradiente1.add(btnAyuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 220, 50));

        btnsalirAd.setBackground(new java.awt.Color(255, 0, 0));
        btnsalirAd.setForeground(new java.awt.Color(0, 0, 0));
        btnsalirAd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes_munus/iconfinder_close_981077.png"))); // NOI18N
        btnsalirAd.setText("Salir");
        btnsalirAd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirAdActionPerformed(evt);
            }
        });
        rSPanelGradiente1.add(btnsalirAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 220, 50));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 51));
        rSPanelGradiente1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 250, 20));

        getContentPane().add(rSPanelGradiente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 248, 756));

        rSPanelGradiente2.setColorPrimario(new java.awt.Color(153, 255, 204));
        rSPanelGradiente2.setColorSecundario(new java.awt.Color(51, 102, 255));
        rSPanelGradiente2.setGradiente(rspanelgradiente.RSPanelGradiente.Gradiente.ESQUINA_4);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-home.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-grafica.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-clock.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/botones/claros/x64-usuario.png"))); // NOI18N

        javax.swing.GroupLayout rSPanelGradiente2Layout = new javax.swing.GroupLayout(rSPanelGradiente2);
        rSPanelGradiente2.setLayout(rSPanelGradiente2Layout);
        rSPanelGradiente2Layout.setHorizontalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap(808, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(36, 36, 36))
        );
        rSPanelGradiente2Layout.setVerticalGroup(
            rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rSPanelGradiente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rSPanelGradiente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        getContentPane().add(rSPanelGradiente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 1130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFacAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacAdminActionPerformed
     new CambiaPanel (Contenedor, new Facturacion()); 
    }//GEN-LAST:event_btnFacAdminActionPerformed

    private void btnInvAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvAdminActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(Contenedor, new Inventario());
    }//GEN-LAST:event_btnInvAdminActionPerformed

    private void btnCliAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliAdminActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(Contenedor, new Clientes());
    }//GEN-LAST:event_btnCliAdminActionPerformed

    private void btnRepAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRepAdminActionPerformed

    private void btnsalirAdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirAdActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login c = new login();
        c.setVisible(true);
    }//GEN-LAST:event_btnsalirAdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private rojerusan.RSButtonIconD btnAyuAdmin;
    private rojerusan.RSButtonIconD btnCliAdmin;
    private rojerusan.RSButtonIconD btnFacAdmin;
    private rojerusan.RSButtonIconD btnInvAdmin;
    private rojerusan.RSButtonIconD btnRepAdmin;
    private rojerusan.RSButtonIconD btnsalirAd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente1;
    private rspanelgradiente.RSPanelGradiente rSPanelGradiente2;
    // End of variables declaration//GEN-END:variables
}
